version: '2'

services:
        postgres:
            build:
                context: .
                dockerfile: Dockerfile-PostgreSQL
            network_mode: "bridge"
        tomcat:
            build:
                context: .
                dockerfile: Dockerfile-Tomcat
            links:
                - postgres:postgres
            ports:
                - "8081:8080"
            network_mode: "bridge"