version: '2'

services:
        postgres:
            image: postgres:latest
            network_mode: "bridge"
        tomcat:
            build:
                context: .
                dockerfile: Dockerfile-Tomcat
            links:
                - postgres:postgres
            ports:
                - "8081:8080"
            network_mode: "bridge"

        # dbl:
        #   build: ./dbl/
        #   ports:
        #    - "8080:8080"
        #   links:
        #    - elda 
        #    - fuseki 
        #    - mongo
        #    - rsyslog
        #   volumes:
        #    - ./dbl-src/src:/var/lib/dbl/app
        #   network_mode: "bridge"
        # mongoPIDsvc:
        #   image: mongo
        #   volumes:
        #    - ./data/:/data/db
        #   network_mode: "bridge"
        # elda:
        #   build: ./elda/
        #   links:
        #    - fuseki
        #    - rsyslog
        #   ports:
        #    - "8086:8080"
        #   network_mode: "bridge"
        # fuseki:
        #   build: ./fuseki/
        #   links:
        #    - rsyslog
        #   ports:
        #    - "8087:3030"
        #   volumes:
        #    - ./tdb:/opt/fuseki/DB 
        #   network_mode: "bridge"
        # rsyslog:
        #   build: ./rsyslog/
        #   ports:
        #    - "8088:80"
        #    - "11514:10514"
        #    - "12514:514"
        #   volumes:
        #    - ./logs/:/var/log
        #   network_mode: "bridge"
