version: '2'

services:
        postgres:
            build:
                context: .
                dockerfile: Dockerfile-PostgreSQL
            volumes:
                - /OSM/MEL/LW_OZNOME/apps/PIDsvc/PIDsvc_db:/var/lib/postgresql/data
            network_mode: "bridge"
        # apache:
        #     build:
        #         image: httpd
        #     network_mode: "bridge"
        tomcat:
            build:
                context: .
                dockerfile: Dockerfile-Tomcat
            links:
                - postgres:postgres
            ports:
                - "8081:8080"
            network_mode: "bridge"